### PR TITLE
Handle invalid UTF-8 and "DEL" ASCII code

### LINKED ISSUE #139: Solution crashes Exercism testing
This solution to "Rational Cipher" is not working, but does something that reproducibly ends in:

> An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break.
> 
> Please check your code, and if nothing seems to be wrong, try running the tests again.

I'm pretty sure this happens because the code produces invalid characters in the return string and there is a problem with those in test runner output JSON.

```php
<?php

declare(strict_types=1);

class RotationalCipher
{
    public function rotate(string $text, int $shift): string
    {
        $textLength = strlen($text);
        for ($i = 0; $i < $textLength; $i++) {
            $text[$i] = chr(ord($text[$i]) + $shift);
        } 

        return $text;
    }
}
```

### PR DESCRIPTION
**Pull request by mk-mxp**
Closes #139

In user output, e.g. for debugging, and in test failure messages there may be invalid UTF-8 or an ASCII DEL character.

Invalid UTF-8 stopped PHP from producing JSON completely. This was found while working on Rotational Cipher, where ASCII characters are rotated and might result in invalid UTF-8.

ASCII DEL character was also produced during that exercise and resulted in wrongly displayed output vs. JSON. PHPUnit detects ASCII control chars and turns output to "binary string" - but not for invisible DEL character (0x7F), which consumes the following character on screen.

### CODE REVIEW

File: src/Result.php [hunk 1]
```diff
@@ -50,11 +50,25 @@ public function jsonSerialize(): mixed
...
         if ($this->userOutput !== '') {
-            $result['output'] = $this->userOutput;
+            // In 2024 some innocent ASCII code still fools displays and editors.
+            $result['output'] = \str_replace(
+                [
+                    "\u{7F}", // Delete
+                ],
+                "\u{FFFD}", // Unicode substitute for invalid characters
+                $this->userOutput
+            );
```
Comment (homersimpsons) [inline src/Result.php:60]: Do we need this if we have `JSON_INVALID_UTF8_SUBSTITUTE`?

File: src/Tracer.php [hunk 2]
```diff
@@ -165,7 +165,9 @@ private function saveResults(): void
             $this->outFileName,
             \json_encode(
                 $this->result,
-                self::DEBUG_PRETTY_JSON ? JSON_PRETTY_PRINT : 0
+                JSON_INVALID_UTF8_SUBSTITUTE | (
+                    self::DEBUG_PRETTY_JSON ? JSON_PRETTY_PRINT : 0
+                )
```
Comment (homersimpsons) [inline src/Tracer.php:170]: I think it would be easier to read as:


```suggestion
                JSON_INVALID_UTF8_SUBSTITUTE
                | (self::DEBUG_PRETTY_JSON ? JSON_PRETTY_PRINT : 0)
```

File: tests/fail-with-invalid-chars-in-message/HelloWorld.php [hunk 3]
```diff
@@ -0,0 +1,11 @@
+<?php
+
+function helloWorld()
+{
+    $invalidChars = [
+        "\u{7F}", // Delete
+        "\xFF\xFF\xFF\xFF\xFF\xFF", // Invalid UTF-8
```
Comment (homersimpsons) [inline tests/fail-with-invalid-chars-in-message/HelloWorld.php:7]: Is it important to have this repetition? Or we could stick to one?


```suggestion
        "\xFF", // Invalid UTF-8
```

**Review by homersimpsons — COMMENTED** [review]
Nice catch and probably nice investigation!

File: src/Result.php (hunk 1 above)
Comment (mk-mxp) [reply src/Result.php:60]: Yes, because this is valid UTF-8. It is not handled by PHPUnit (which turns other occurences of invisible characters < 0x1F into hexadecimal string representation (`bin2hex()`). But this characters eats the character after it, and so becomes a debugging nightmare for beginners. And me.

File: tests/fail-with-invalid-chars-in-message/HelloWorld.php (hunk 3 above)
Comment (mk-mxp) [reply tests/fail-with-invalid-chars-in-message/HelloWorld.php:7]: UTF-8 uses bit 8 in `\xFF` to say: the next byte adds to this character. So whatever follows a single `\xFF` is valid UTF-8. To become invalid, a sequence of 6 `\xFF` bytes is required, as UTF-8 may have up to 6 bytes but never 7.

File: src/Result.php (hunk 1 above)
Comment (homersimpsons) [reply src/Result.php:60]: Thanks for the explanation! Would it be better to cast it to a unicode representation instead of an invalid character?

**Review by homersimpsons — APPROVED** [review]

File: src/Result.php (hunk 1 above)
Comment (mk-mxp) [reply src/Result.php:60]: I'm not sure if `U+2421 ␡` is actually more helpful than `U+FFFD �` to students. In my terminal the Unicode graphical representation ␡ does not always show up. It is displayed by `cat` when used in the PHP file, but not printed when running the tests in Docker. It ends up in the JSON correctly encoded. But there is quirks, and I'd stick with the very old � for our purpose ("this char is not expected to be here").
